---
output: html_document
---

# Cirriculum Vitea

Mijn naam is Anna en ik ben vierdejaars bachelor student Life Sciences aan de Hogeschool Utrecht met een specialisatie in Microbiologie en een minor in Data Science. Ik ben sociaal, gemotiveerd en nieuwsgierig en ik kijk er heel erg naar uit om mijn kennis in de praktijk toe te passen.

**Contactgegevens**

-   Naam: Anna van Donkersgoed

-   Mail: anna.van.donkersgoed\@student.hu.nl

**Talen**

-   Nederlands (moedertaal)

-   Engels

**Opleidingen**

| Jaar | Diploma | School | Plaats |
|----|----|----|----|
| 2020-heden | Life Sciences | Hogeschool Utrecht | Utrecht, Nederland |
| 2021 | Propedeuse Life Sciences | Hogeschool Utrecht | Utrecht, Nederland |
| 2015-2020 | HAVO | Anna van Rijn college | Nieuwegein, Nederland |

**Technieken en vaardigheden**

-   MALDI-TOF
-   PCR
-   Vitek
-   Bacteriekweek + anaëroob kweken
-   MIC bepaling
-   CelkweekNGS
-   dataverwerking
-   Metagenomics dataverwerking
-   R
-   bask
-   Excel

**Project vaardigheden**

Project Parodontitis

-   Effect van ijzer op de binding van *Porphyromonas gingivalis* aan verschillende aan verschillende oppervlakten.
-   Toepassing van anaërobe technieken (bactron600).
-   Ontwikkeling van flexibiliteit in een onderzoeksaanpak.

**Project Antimicrobiële resistentie**

-   Ontwikkeling van een bioinformatica pipeline voor analyse van antimicrobiële resistentie.
-   Data visualisatie d.m.v. een interactieve R shiny app.
-   Toepassing van GitHub.
-   Projectplanning en samenwerken in een Agile omgeving.

**Werkervaring**

| Jaar | Functie | Bedrijf | Plaats |
|----|----|----|----|
| 2025 | Medewerker centrale omsterontvanges | AQUON | Houten, Utrecht |
| 2022-2024 | Horecamedewerker | DE KOM, stadstheater en kunstcentrum | Nieuwegein, Utrecht |
| 2019-2021 | Vakkenvuller | Boon's mark | Nieuwegein, Utrecht |

**Vrijwilligerswerk**

| Jaar | Vrijwilligerswerk | Organisatie | Plaats |
|----|----|----|----|
| 2021-2025 | Leiding, leeftijd 7-12 jaar | Scouting Jan van Hoof | Nieuwegein, Utrecht |
| 2019-2021 | Leiding, leeftijd 5-7 jaar | Scouting Jan van Hoof | Nieuwegein, Utrecht |

**Competenties**

-   Flexibel

-   Oplossingsgericht

-   Samenwerken

-   Organiseren
