---
output: html_document
---

# Plan voor de toekomst 

Tijdens mijn opleiding ben ik erachter gekomen dat ik graag op het laboratorium sta en dat mijn interesse ligt in micro-organismen. Het zou mij dus heel erg leuk lijken om hiermee te werken en dit te combineren met datascience door bijvoorbeeld zelfverkregen data uit te werken of scripts te schrijven om dataverwerking te optimaliseren. Mijn droombaan op dit moment is om research technician te zijn bij een onderzoeksgroep om hierbij nieuwe dingen te leren en mensen te helpen. Qua vakgebied zijn er heel veel dingen interessant, maar wat voor nu na mijn stage mijn interesse heeft is de rol van bacteriën in kankeronderzoek. Daarnaast lijkt het me erg leuk om zelf biologische samples te sequencen en data daarvan uit te werken of microscopische afbeeldingen maken en deze uit te werken. Op dit moment heb ik de basisvaardigheden, aangezien ik kan werken met R in Rstudio. Daarnaast heb ik tijdens de cursussen van de minor Next Generation Sequencing data uitgewerkt en metagenomics, wat veel wordt gebruikt in het vak met micro-organismen. Om mijn droombaan te kunnen bereiken is het handig als ik python leer, aangezien die programmeertaal in veel vacatures staat. Daarnaast wil ik technieken zoals single cell RNA sequencing data uit kunnen werken en me bezig houden met cancer genomics om het effect van bacteriën op kankercellen te kunnen analyseren. Daarnaast moet ik meer gaan oefenen met het automatiseren van analyses. Een deel daarvan zal ik in deze cursus gaan leren, maar de rest zal ik zeker in mijn vrije tijd moeten gaan doen. 

