---
output: html_document
---


# Introductie project AMR

**Introductie project antimicrobiële resistentie**


Micro-organismen kunnen infecties veroorzaken. Om deze infecties te voorkomen of behandelen worden er microbiële middelen gebruikt. Dit zijn middelen die voor decennia gebruikt zijn, met in het begin groot succes. Echter is gebleken dat micro-organismen resistentie kunnen ontwikkelen tegen deze middelen, wat een groot probleem veroorzaak. Hierdoor raken ze ongevoelig tegen medicatie en is het lastiger om de patiënt te behandelen. Het resistent worden tegen microbiële middelen heet antimicrobiële resistentie (AMR) [@brinkacThreatAntimicrobialResistance2017; @ResistenteMicroorganismenRIVM]. Bacteriën vallen ook onder micro-organismen en kunnen resistentie vertonen door twee hoofdmechanismes. Ze kunnen al resistent zijn voordat de behandeling begint of ze kunnen resistentie ontwikkelen over een bepaalde tijdsperiode heen [@reygaertOverviewAntimicrobialResistance2018]. Daarnaast kunnen bacteriën resistentie met elkaar uitwisselen. Dit gebeurd doordat bacteriën horizontaal een resistoom kunnen uitwisselen waar de resistentiegenen opzitten [@burmeisterHorizontalGeneTransfer2015]

Om het AMR probleem aan te pakken zijn er meerdere sectoren nodig om kennis uit te wisselen. Dit wordt gedaan door het One Health approach. Deze aanpak streeft naar het verbeteren en optimaliseren van de gezondheid van mensen, dieren en het milieu [@AntimicrobialResistance]. In dit project wordt er een pipeline gemaakt om de uitwisseling van het resistoom door Nederland te monitoren. Hierbij wordt er de pipeline gemaakt van een al bestaande workflow en worden er ook applicaties toegevoegd. Uiteindelijk moet de data gevisualiseerd worden in een Rshiny app. Daarnaast gaat dit project ook over samenwerken volgens de Guerilla Analytics [@GuerrillaAnalytics2014a]. Dit wordt gedaan door version control software, sprints, goede planning en communicatie aangezien er met een externe opdrachtgever gewerkt wordt. 
