---
title: "Source_listing_introduction"
output: html_document
---


# Introductie project AMR

**Introductie project antimicrobiële resistentie**

Tegenwoordig worden er veel antimicrobiële middelen gebruikt om infectie ziekten te behandelen en te voorkomen. Antibiotica, antivirale middelen en antiparasitaire middelen zijn voorbeelden hiervan (source). Echter komt resistentie vanuit bacteriën tegen deze middelen steeds vaker voor. Dit kan komen doordat de resistentie tegen het antimicrobieel middel al aanwezig is, of doordat het overtijd ontwikkeld (source). Het resistent worden tegen bacteriën heet antimicrobiële resistentie @OneHealthRIVM. Antimicrobiële resistentie is een wereldwijn probleem (source). Een mogelijke oplossing hiervoor is de OneHealth approach. Dit houd in dat mensen vanuit verschillende secotren samenwerken om een oplossing te vinden om deze resistentie te verminderen. Onder deze secotren vallen de voedselproductie, dier-en milieusector en gezondheidssector. Het is belangrijk dat sectoren samen werken, aangezien ziektes ook overgrdragen kunnen worden door verschillende sectoren, zoals bij mensen en dieren. 

In dit project wordt gekeken naar de uitwisselingen van resistooms tussen bacteriën. In het resistoom zitten genen die voor resistentie zorgen. Deze kunnen horizontaal overgedragen worden (source). In dit geval wordt er specifiek gekeken naar de uitwisseling in Nederland. 

