---
title: "Reproducible_Science_Article"
output: html_document
---

In dit gedeelte van het portfolio wordt er gekeken naar reproduceerbaarheid vanuit artikelen die online staan. Eerst wordt het artikel gelezen en wordt er een samenvatting over gemaakt. 

## Artikel informatie 

Artikel: Small Intestine Bacterial Overgrowth is associated with increased Campylobacter and epithelial injury in duodenal biopsies of Bangladeshi children

Environmental enteric dysfonction (EED) is een asymptomatisch syndroom waarbij de dunne darm ontstoken raakt en niet meer effectief nutriënten kan opnemen, wat kan zorgen voor een negatieve impact op de groei en ontwikkeling van kinderen. Dit syndroom komt veel voor in lagen- en middeninkomtslanden, waarbij slechte hygiëne vaak aanwezig is. Het is gevonden dat een deel van de kinderen met EED small intestine bacterial overgrowth (SIBO) hebben, een dysbiose waarbij er teveel bacteriën in de dunne darm groeien. Het doel van dit onderzoek was om te bepalen of SIBO en EED een verband hadden in kinderen uit Bangladesh met als hypothese dat er een verband is en dat mucosa-adherende bacteriën significant zouden verschillen in SIBO positieve kinderen en SIBO negatieve kinderen. 

De kinderen werden geselecteerd op bepaalde ciriteria, esophagogastroduodenoscopy werd uitgevoerd en bbiopsies van de twaalfvingerige darm werden genomen. Deze biopsies werden gelijk onderzocht onder de microscoop en daarna bewaard voor DNA extractie, gevolgd door 16srRNA gene sequencing. Voor de histlogische analyses werden de biopsies gefixeerd en werden de weefselcoupes beoordeeld volgens een index gerelateerd met de mate van ontsteking van de dunne darm. SIBO werd getest door glucose-hydrogen-breath testing (GHBT) en de samples werden geanalyseerd door gas chromatografie. De samples werden ingedeeld in SIBO positief of SIBO negatief. Statistische analyses werden uitgevoerd door te kijken naar non-parametische testen, alphaa- en bèta diversiteit.

Van de geteste kinderen hadden 12.7% SIBO, en er werd geen significan verschil gevonden tussen de histologische elementen tussen SIBO positieve en SIBO negatieve kinderen. Wat opviel was dat kinderen met SIBO een veel hogere abundantie hadden in Campylobacter dan kinderen zonder SIBO en dat verhoogde SIBO in verband stond met enterocytbeschadiging. 

## reproduceerbaarheid articel 

In het tweede gedeelte wordt het artikel beoordeeld op repoduceerbaarheid waarbij er gekeken wordt naar verschillende beoordelingscriteria. 

Over het algemeen is het artikel reproduceerbaar. Het doel is duidelijk weergeven aan het einde van de inleiding, er wordt aangegeven waar de data gevonden kan worden en dat alle data, metadata en code die gebruikt is in de studie gevonden kan worden. Er wordt aangegeven waar de studie is uitgevoerd en hoe de first author bereikt kan worden. Ook staat er een etische statement en een funding statement en is de code makkelijk te gebruiken. De algemene indruk is dus erg positief. 

## reproduceerbaarheid R code 

Om te kijken of de code ook reproduceerbaar is voer ik de code van het artikel zelf uit om dezelfde resultaten te krijgen als de figuren. De data is te downloaden via een zip bestand. Wat me gelijk opviel was dat er geen README aanwezig was en het ook niet duidelijk was welk script voor welk doel gebruikt was. In de zip folder zat een R script, een Rmarkdown bestand, een R object en 5 datasets. Het R script was wat onduidelijk, maar het Rmarkdown bestand was makkelijk te lezen, aangezien er veel pseudocoding werd gebruikt om de verschillende stappen uit te leggen. 

In het Rmarkdown bestand werden de verschillende analyses uitgevoerd. Nadat de data was ingeladen werden datasets samengevoegd en werden de verschillende taxa gefilterd. Daarna werden alpha en beta diversity analyses uitgevoerd om te kijken naar het verschil in SIBO positieve en SIBO negatieve kinderen. Alpha diversity werd gemeten met de Shannon index en de Wilcoxon test werd uitgevoerd om te kijken of er een singificant verschil is. Daarna werd er gekeken naar de beta diversity door een Principle Coordinates Analysis (PCoA) uit te voeren. Nadat er werd gekeken naar de significantie tussen de verschillende taxa met de de DESeq2 package in R. The area under the curve at 50% was calculated and split into two groups, low and high. Daarna werden verschillende. Daarna werden de histologische resultaten vergeleken met 16srRNA doormiddel van een PERMANOVA test, specifiek voor twee histologische parameters. Hierbij werden de alpha en beta diversity op dezelfde manier als eerder benoemd berekend. Als laatste in de anlayse werd de algemene microbiële compositie onderzocht. Hierbij werden de taxa op phylum level uitgeplot waarbij er naar de abudantie werd gekeken. 

Tijdens het uitvoeren van het markdown bestand kwam ik tegen wat kleine dingen aan. Als eerst zou ik de packages installeren in de code, aangezien dit nu handmatig gedaan moest worden. Daarnaast stonden de datasets in de code in een ander format dan in de folder. Ook kwamen sommige pathways met het inlezen van de data niet overeen met de folderstructuur. Dit zijn dingen die je makkelijk zelf kan aanpassen, wat wel zorgt voor een mindere reproduceerbaarheid. Wat heel fijn was aan dit Rmarkdown bestand was dat als eenmaal alles goed staat de code werkte. De grafieken die uit de bestanden kwamen, waren echter anders dan de grafieken die in het artikel staan, zie figuur x. Daarnaast waren er datasets in de folder, alleen stond er geen duidelijke uitleg bij wat welke dataset inhield. 

Op een schaal van 1 tot 5 geef ik de reproduceerbaarheid van de R code een 3, aangezien niet alles duidelijk is weergeven, maar er wel pseudocoding met uitleg staat. Om op deze manier te kijken naar een artikel besef je zelf hoe lastig het is om goed reproduceerbaar te werken, wat goed inicht geeft. 


